#!/bin/sh
USEDIRS=
COMMAND=
for x in $*; do
    if [ -f ${x}/.git ]; 
    then USEDIRS="${USEDIRS} ${x}";
    else COMMAND="${COMMAND} ${x}";
    fi;
done;
if [ -z "${USEDIRS}" ]; then
    for dir in *; do
	if [ -d ${dir} ] && [ ! -f ${dir}.skip ] && [ -d ${dir}/.git ]; then
	    USEDIRS="${USEDIRS} ${dir}";
	fi;
    done;
fi;
echo "USEDIRS=${USEDIRS}";
echo "COMMAND=${COMMAND}";
for dir in ${USEDIRS}; do
    command cd ${dir}; ${COMMAND}; command cd ..; done;
