#!/bin/sh
ALLDIRS="hyphenate imagetools sundown tidy zeromq nng ziptools"
DIRS=
ROOT=$(pwd)
ARGS=
if [ $# = 1 ]; then
    if [ -d $1 ]; then
	DIRS=$1;
	ARGS=;
    else
	DIRS=${ALLDIRS};
	ARGS=$*;
    fi;
else while [ $# -gt 0 ]; do
	 if [ -d $1 ]; then
	     DIRS="${DIRS} $1";
	 else
	     ARGS="${ARGS} $1";
	 fi;
	 shift; done;
fi;
if [ -z "$DIRS" ]; then
    DIRS=${ALLDIRS};
fi;
# Just in case
make symlinks
# Switch branches
BRANCH=$(cat .branch || u8_gitbranch || echo main)
for dir in ${DIRS}; do command cd ${dir}; git checkout ${BRANCH}; command cd ..; done;
# Do all the targets on all the directories, using the current versions of knoconfig and knobuild
for dir in ${DIRS}; do
    if [ ! -f ${dir}.skip ]; then
	make -C ${dir} KNOCONFIG="${ROOT}/knoconfig" KNOBUILD="${ROOT}/knobuild" ${ARGS};
    fi;
done
