#!/bin/sh
ALLEXTMODS="hyphenate leveldb rocksdb mongodb postgres mariadb odbc nng zeromq archivetools imagetools mod_knocgi sundown tidy ziptools"
EXTMODS="hyphenate leveldb rocksdb imagetools mariadb odbc archivetools postgres zeromq mod_knocgi sundown tidy mongodb nng ziptools"
DIRS=
ROOT=$(pwd)
ARGS=
if [ $# = 1 ]; then
    if [ -d $1 ]; then
	DIRS=$1;
	ARGS=;
    else
	DIRS=${EXTMODS};
	ARGS=$*;
    fi;
else while [ $# -gt 0 ]; do
	 if [ -d $1 ]; then
	     DIRS="${DIRS} $1";
	 else
	     ARGS="${ARGS} $1";
	 fi;
	 shift; done;
fi;
if [ -z "$DIRS" ]; then
    DIRS=${EXTMODS};
fi;
# Just in case
make symlinks
# Switch branches
BRANCH=$(cat .branch 2>/dev/null|| u8_gitbranch)
if [ -n "${BRANCH}" ]; then
    for dir in ${DIRS}; do ("cd" ${dir}; git checkout ${BRANCH}); done;
fi;
# Do all the targets on all the directories, using the current versions of knoconfig and knobuild
FAILED=
for dir in ${DIRS}; do
    if [ ! -f ${dir}.skip ]; then
	("cd" ${dir}; 
	 echo "Submake ${dir}";
	 make KNOCONFIG="${ROOT}/knoconfig" KNOBUILD="${ROOT}/knobuild" ${ARGS}) || 
	    FAILED="${dir} ${FAILED}";
    fi;
done
if [ ! -z "${FAILED}" ]; then
    echo "Failed builds: ${FAILED}";
fi;
