#!/bin/sh
CONTRIBS=$(cat ./ENABLED 2>/dev/null)
for dir in ${CONTRIBS}; do
    if [ -f ${dir}/.skip ]; then
	:;
    elif [ -d ${dir}/.git ]; then
	("cd" ${dir};
	 echo "# In ${dir}";
	 git "$@");
    fi;
done
