#!/bin/sh
CONTRIBS=$(cat ./ENABLED 2>/dev/null)
echo "Args=$*";
for dir in ${CONTRIBS}; do
    if [ -f ${dir}/.skip ]; then
	:;
    elif [ -d ${dir}/.git ]; then
	("cd" ${dir};
	 echo "# In ${dir}"
	 "$@";)
    fi;
done
