#!/bin/sh

rmconf () {
    echo rmconf $1
    if test -f $1; then
	base=$(basename $1 .in)
	dir=$(dirname $1)
	if test -f ${dir}/${base}; then
	    rm -f ${dir}/${base}; 
	fi;
    fi;}

for x in *.in */*.in */*/*.in */*/*/*.in; do rmconf ${x}; done

find . -name "*~" -type f -writable -exec rm '{}' \;
find . -name "#*#" -type f -writable -exec rm '{}' \;
find . -name "*.o" -type f -writable -exec rm '{}' \;
find . -name "*.gcda" -type f -writable -exec rm '{}' \;
find . -name "*.gcno" -type f -writable -exec rm '{}' \;
find . -name "*.gcov" -type f -writable -exec rm '{}' \;
find . -name "*.bb" -type f -writable -exec rm '{}' \;
find . -name "*.bbg" -type f -writable -exec rm '{}' \;
find . -name "*.da" -type f -writable -exec rm '{}' \;
find . -name "gmon.out" -writable -exec rm '{}' \;
# find . -name "*.gcda" -type f -writable | xargs rm -f
# find . -name "*.gcno" -type f -writable | xargs rm -f
# find . -name "*.gcov" -type f -writable | xargs rm -f
# find . -name "*.bb" -type f -writable | xargs rm -f
# find . -name "*.bbg" -type f -writable | xargs rm -f
# find . -name "*.da" -type f -writable | xargs rm -f
# find . -name "gmon.out" -writable | xargs rm -f

# Miscellaneous files
find . -name "*.dSYM" -writable | xargs rm -rf;

for pat in *.gcda *.gcno *.gcov *.bb *.bbg *.da gmon.out *.heap; do
    find -name ${pat} -writable -exec rm '{}' \; ;
done;

rm -f config.log config.status buildmode;

rm -rf etc/*.o etc/.libs;
rm -f lib/*.a lib/*@suffix@.so* lib/*.dylib;
rm -f lib/kno/*@suffix@.so* lib/kno/*.dylib;
rm -f exe/knox@suffix@ exe/knotask@suffix@;
rm -f exe/knosrv@suffix@ exe/knod@suffix@;
rm -f exe/knosh@suffix@ exe/knocgi@suffix@;
rm -f *TAGS;

for file in tests/types/*.c \
		tests/storage/*.c \
		tests/scheme/*.c; \
    do if test -f ${file}; then \
	   rm -f $(basename ${file} .c) \
	         $(basename ${file} .c).shared; \
       fi; \
    done;

rm -f tests/scheme/*.pool tests/scheme/*.index tests/scheme/*.log
rm -f tests/scheme/*.dtype tests/scheme/_countup.*

rm -f makefile config.log config.status config.cache;
rm -f tests/types/makefile tests/storage/makefile tests/scheme/makefile;
rm -f tests/types/.gdbinit tests/storage/.gdbinit tests/scheme/.gdbinit;
rm -f etc/knogetconfig etc/knosetconfig etc/kno-rc.d;
rm -f exe/.gdbinit include/kno/config.h include/kno/revision.h;
