#!/bin/sh

rmconf () {
    echo rmconf $1
    if test -f $1; then
	base=$(basename $1 .in)
	dir=$(dirname $1)
	if test -f ${dir}/${base}; then
	    rm -f ${dir}/${base}; 
	fi;
    fi;}

for x in *.in */*.in */*/*.in */*/*/*.in; do rmconf ${x}; done

find . -name "*~" -writable -exec rm '{}' \;
find . -name "#*#" -writable -exec rm '{}' \;
find . -name "*.o" -writable -exec rm '{}' \;

# Miscellaneous files
find . -name "*.dSYM" -writable | xargs rm -rf;

for pat in *.gcda *.gcno *.gcov *.bb *.bbg *.da gmon.out *.heap; do
    find -name ${pat} -writable -exec rm '{}' \; ;
done;

rm -f config.log config.status buildmode;

rm -rf etc/*.o etc/.libs;
rm -f lib/*.a lib/*@suffix@.so* lib/*.dylib;
rm -f lib/framerd/*@suffix@.so* lib/framerd/*.dylib;
rm -f exe/fdexec@suffix@ exe/fdbatch@suffix@;
rm -f exe/fdservlet@suffix@ exe/fdserver@suffix@;
rm -f exe/fdconsole@suffix@ exe/fdcgiexec@suffix@;
rm -f *TAGS;

for file in tests/types/*.c \
		tests/storage/*.c \
		tests/scheme/*.c; \
    do if test -f ${file}; then \
	   rm -f $(basename ${file} .c) \
	         $(basename ${file} .c).shared; \
       fi; \
    done;

rm -f tests/scheme/*.pool tests/scheme/*.index tests/scheme/*.log
rm -f tests/scheme/*.dtype tests/scheme/_countup.*

rm -f makefile config.log config.status config.cache;
rm -f tests/types/makefile tests/storage/makefile tests/scheme/makefile;
rm -f tests/types/.gdbinit tests/storage/.gdbinit tests/scheme/.gdbinit;
rm -f etc/fdgetconfig etc/fdsetconfig etc/framerd-rc.d;
rm -f exe/.gdbinit include/framerd/config.h include/framerd/revision.h;
