.\" Process this file with
.\" groff -man -Tascii fdscript.1
.\"
.TH LIST-FILE-POOL 1 "MARCH 2002" FramerD "FramerD Documentation"
.SH NAME
list-file-pool \- describes a FramerD file pool
.SH SYNOPSIS
.B list-file-pool
.I filename 
.SH DESCRIPTION
.B list-file-pool
describes the FramerD file pool in the file
.I filename
.SH OPTIONS
No options
.SH DIAGNOSTICS
The program reports an error if
.I filename
does not exist or is not a file pool.
.SH BUGS
No known bugs.
.SH Revision Info
.B $Id: list-file-pool.1,v 1.3 2002/07/10 00:13:11 haase Exp $
.SH AUTHOR
Ken Haase < kh@beingmeta.com >
.SH "SEE ALSO"
.BR framerd (7)
.BR make-file-pool (1)
