.\" Process this file with
.\" groff -man -Tascii fdscript.1
.\"
.TH MAKE-DTYPE 1 "MARCH 2002" FramerD "FramerD Documentation"
.SH NAME
make-dtype \- write a DType representation of an object to a file
.SH SYNOPSIS
.B make-dtype
.I filename
.B    
.I lisp_expression
.SH DESCRIPTION
.B make-dtype
calls the FramerD lisp parser on 
.I lisp_expression
and writes the corresponding object to the file 
.I filename 
.SH OPTIONS
No options
.SH DIAGNOSTICS
The program reports an error if
.I filename
cannot be written.
.SH BUGS
No known bugs.
.SH Revision Info
.B $Id: make-dtype.1,v 1.3 2002/07/10 00:13:11 haase Exp $
.SH AUTHOR
Ken Haase < kh@beingmeta.com >
.SH "SEE ALSO"
.BR framerd (7)



