(TAGTEST
   "The cereal makers insist that their products are a bargain,\r\nparticularly with discount coupons. Even without them, the\r\nindustry estimates that the average cost of a bowl of cereal,\r\nincluding milk, is about 35'. Yet shoppers who watch their\r\nfamilies gobble up a $5 box of cereal in a couple of sittings\r\nstill consider the cost to be considerable. Ann Rhodes, a mother\r\nwith three children at home in Waterford Township, Michigan,\r\nsays of her family, which can shred seven boxes of cereal\r\nweekly, \"The 14-year-old will eat a whole box if you let him,\r\nand the 11-year-old isn't far behind. It has really gotten\r\nexpensive. Cutting prices would get us to buy more.\"")
(TAGTEST
   "Giuliani took immediate political heat for the response and his\r\npredictably gruff defense of the N.Y.P.D. But the Busch shooting\r\nreflects a chronic problem, one that affects communities\r\nthroughout the country. Increasingly, police action appears to be\r\nthe only action that can be taken with EDPs. \"Law-enforcement\r\nofficers are serving as front-line mental-health workers,\" says\r\nMary Zdanowicz, executive director of the Treatment Advocacy\r\nCenter, based in Virginia. \"But by the time the police intercede,\r\nit's usually too late.\"")
(TAGTEST
   "Where I come from, they call that hush money. But just after New\r\nYear's Day, Stanford told me last week, a reporter from the\r\nEnquirer came to her L.A. home offering \"up to a million\" in\r\nexchange for her story. She says she declined. But as Stanford\r\nnotes, there are plenty of  disgruntled former Rainbow staff\r\nmembers around who \"hate Jesse and want to destroy him\" so much\r\nthey didn't need cash as an incentive to spill what they knew. It\r\nwas Jackson, in his arrogance, who provided them with the\r\nsqualid tale that may bring him down. To appropriate one of\r\nJackson's slogans, his time has gone.")
(TAGTEST
   "By week's end, a sense of panic had crept from the 24-hr.\r\n\"Terror in the Rockies\" broadcasts into the statehouses as well.\r\nSome were more panicked than others: California Governor Gray\r\nDavis spoke of the importance of guidance counselors, but,\r\nreflecting the differences in the men and their states, Virginia\r\nGovernor Jim Gilmore ordered superintendents to report any\r\npotentially dangerous student to police immediately. School\r\ndistricts are alarmed by the governmental consternation. Just\r\nlast week, 150 calls were directed to Russ Ebersole, who runs a\r\nsmall but suddenly lucrative Bethesda, Md., firm that takes $500\r\nfrom schools to bring in Labrador retrievers that sniff out\r\nbombs and gunpowder. Even so, after the worst school massacre in\r\nthis country's history, there must be something we can do. Right?")
(TAGTEST "Other Voices")
(TAGTEST
   "Without preamble, the three-piece band cuts loose. In the\r\nspotlight, the lanky singer flails furious rhythms on his\r\nguitar, every now and then breaking a string. In a pivoting\r\nstance, his hips swing sensuously from side to side and his\r\nentire body takes on a frantic quiver, as if he had swallowed a\r\njackhammer. Full-cut hair tumbles over his forehead, and\r\nsideburns frame his petulant, full-lipped face. His style is\r\npartly hillbilly, partly socking rock 'n' roll. His loud\r\nbaritone goes raw and whining in the high notes, but down low it\r\nis rich and round. As he throws himself into one of his\r\nspecialties--Heartbreak Hotel, Blue Suede Shoes or Long Tall\r\nSally--his throat seems full of desperate aspirates (\"Hi want\r\nyou, hi need you, hi luh-huh-huh-huv yew-hew\") or hiccuping\r\nglottis strokes, and his diction is poor. But his movements\r\nsuggest, in a word, sex.")
(TAGTEST
   "At the same time, it's worth recognizing that the efforts of the\r\nU.S. government and others to get people to live in multinational\r\nand multiethnic communities are more often than not exercises in\r\nfutility. Instead, it is often wise to accommodate those pushing\r\nfor ethnic separation, segregation and homogenization--even if\r\nthat means partitioning entire nations to reduce violence.")
(TAGTEST
   "\r\n\r\nRADICAL CHIC\r\nDjindjic has a Ph.D. in philosophy. During Tito's iron rule, his\r\nstudent activism led to his arrest\r\n\r\nSHARPLY DRESSED \r\nTall and elegantly attired, Djindjic looks different from the\r\ngauche, lumpy apparatchiks who surrounded Slobo \r\n\r\nDICK MORRIS?\r\nDjindjic has a sharp political mind. Insiders credit him with\r\nfine-tuning the street strategy that dumped Milosevic \r\n\r\nCLEAR VIEW\r\nDjindjic says he wants Serbia to have a transparent political\r\nsystem--a necessity for joining Europe's economy\r\n\r\n\r\n")
