exp_exec_prefix = /usr
exp_bindir = /usr/bin
exp_sbindir = /usr/sbin
exp_libdir = /usr/lib
exp_libexecdir = /usr/libexec/apache2
exp_mandir = /usr/share/man
exp_sysconfdir = /private/etc/apache2
exp_datadir = /Library/WebServer
exp_installbuilddir = /usr/share/httpd/build
exp_errordir = /usr/share/httpd/error
exp_iconsdir = /usr/share/httpd/icons
exp_htdocsdir = /Library/WebServer/Documents
exp_manualdir = /Library/WebServer/share/httpd/manual
exp_cgidir = /Library/WebServer/CGI-Executables
exp_includedir = /usr/include/apache2
exp_localstatedir = /private/var
exp_runtimedir = /private/var/run
exp_logfiledir = /private/var/log/apache2
exp_proxycachedir = /private/var/run/proxy
EGREP = /usr/bin/grep -E
PCRE_LIBS = -L/usr/lib -lpcre
SHLTCFLAGS =
LTCFLAGS = -mdynamic-no-pic
MKINSTALLDIRS = /usr/share/httpd/build/mkdir.sh
INSTALL = $(LIBTOOL) --mode=install /usr/share/httpd/build/install.sh -c
MATH_LIBS =
CRYPT_LIBS =
DTRACE = true
PICFLAGS =
PILDFLAGS =
INSTALL_DSO = yes
ab_CFLAGS = -I/usr/local/libressl/include
ab_LDFLAGS = -L/usr/lib -lssl.35 -lcrypto.35 -lpthread
NONPORTABLE_SUPPORT = checkgid fcgistarter
progname = httpd
OS = unix
SHLIBPATH_VAR = DYLD_LIBRARY_PATH
AP_BUILD_SRCLIB_DIRS =
AP_CLEAN_SRCLIB_DIRS =
HTTPD_VERSION = 2.4.18
HTTPD_MMN = 20120211
bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
cgidir = ${datadir}/CGI-Executables
logfiledir = ${localstatedir}/log/apache2
exec_prefix = ${prefix}
datadir = /Library/WebServer
localstatedir = /private/var
mandir = ${prefix}/share/man
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec/apache2
htdocsdir = ${datadir}/Documents
manualdir = ${datadir}/share/httpd/manual
includedir = ${prefix}/include/apache2
errordir = ${prefix}/share/httpd/error
iconsdir = ${prefix}/share/httpd/icons
sysconfdir = /private/etc/apache2
installbuilddir = ${prefix}/share/httpd/build
runtimedir = ${localstatedir}/run
proxycachedir = ${runtimedir}/proxy
other_targets =
progname = httpd
prefix = /usr
AWK = awk
CC = /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.11.xctoolchain/usr/bin/cc
CPP = /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.11.xctoolchain/usr/bin/cc -E
CXX =
CPPFLAGS =
CFLAGS =
CXXFLAGS =
LTFLAGS = --silent
LDFLAGS =
LT_LDFLAGS =
SH_LDFLAGS =
LIBS =
DEFS =
INCLUDES =
NOTEST_CPPFLAGS =
NOTEST_CFLAGS =
NOTEST_CXXFLAGS =
NOTEST_LDFLAGS =
NOTEST_LIBS =
EXTRA_CPPFLAGS = -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1
EXTRA_CFLAGS =
EXTRA_CXXFLAGS =
EXTRA_LDFLAGS =
EXTRA_LIBS =
EXTRA_INCLUDES = -I$(includedir) -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1
INTERNAL_CPPFLAGS =
LIBTOOL = /usr/share/apr-1/build-1/libtool --silent
SHELL = /bin/sh
RSYNC = /usr/bin/rsync
SH_LIBS =
SH_LIBTOOL = $(LIBTOOL)
MK_IMPLIB =
MKDEP = $(CC) -MM
INSTALL_PROG_FLAGS =
ENABLED_DSO_MODULES = ,authn_file,authn_core,authz_host,authz_groupfile,authz_user,authz_core,access_compat,auth_basic,reqtimeout,filter,mime,log_config,env,headers,setenvif,version,proxy,proxy_connect,proxy_ftp,proxy_http,proxy_fcgi,proxy_scgi,proxy_wstunnel,proxy_ajp,proxy_balancer,proxy_express,slotmem_shm,lbmethod_byrequests,lbmethod_bytraffic,lbmethod_bybusyness,lbmethod_heartbeat,unixd,status,autoindex,dir,alias
LOAD_ALL_MODULES = no
APR_BINDIR = /usr/bin
APR_INCLUDEDIR = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1
APR_VERSION = 1.4.8
APR_CONFIG = /usr/bin/apr-1-config
APU_BINDIR = /usr/bin
APU_INCLUDEDIR = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1
APU_VERSION = 1.5.2
APU_CONFIG = /usr/bin/apu-1-config
