/* -*- Mode: C;  Character-encoding: utf-8; -*- */

#ifndef KNO_PQPRIMS_H
#define KNO_PQPRIMS_H 1
#ifndef KNO_PQPRIMS_H_INFO
#define KNO_PQPRIMS_H_INFO "include/kno/sql.h"
#endif

static struct KNO_SQLDB_HANDLER postgres_handler;

typedef struct KNO_PQCONN {
  KNO_SQLCONN_FIELDS;
  int pqconn_n_params;
  char **pqconn_keys;
  char **pqconn_vals;
  struct KNO_HASHTABLE pqconn_oids;
  u8_mutex pqconn_lock;
  lispval pqconn_raw;
  PGconn *pqconn;} KNO_PQCONN;
typedef struct KNO_PQCONN *kno_pqconn;

typedef struct KNO_PQCONN *pqconn;

typedef struct KNO_PQPROC {
  KNO_SQLPROC_FIELDS;
  u8_mutex pqproc_lock;
  int pqproc_n_cols, pqproc_needs_init;} KNO_PQPROC;
typedef struct KNO_PQPROC *kno_pqproc;

#define PQTYPE_BOOL 16
#define PQTYPE_BYTEA 17
#define PQTYPE_CHAR 18
#define PQTYPE_NAME 19
#define PQTYPE_INT8 20
#define PQTYPE_INT2 21
#define PQTYPE_INT2VECTOR 22
#define PQTYPE_INT4 23
#define PQTYPE_REGPROC 24
#define PQTYPE_TEXT 25
#define PQTYPE_OID 26
#define PQTYPE_TID 27
#define PQTYPE_XID 28
#define PQTYPE_CID 29
#define PQTYPE_OIDVECTOR 30
#define PQTYPE_PG_TYPE 71
#define PQTYPE_PG_ATTRIBUTE 75
#define PQTYPE_PG_PROC 81
#define PQTYPE_PG_CLASS 83
#define PQTYPE_JSON 114
#define PQTYPE_XML 142
#define PQTYPE_PG_NODE_TREE 194
#define PQTYPE_PG_NDISTINCT 3361
#define PQTYPE_PG_DEPENDENCIES 3402
#define PQTYPE_PG_MCV_LIST 5017
#define PQTYPE_PG_DDL_COMMAND 32
#define PQTYPE_POINT 600
#define PQTYPE_LSEG 601
#define PQTYPE_PATH 602
#define PQTYPE_BOX 603
#define PQTYPE_POLYGON 604
#define PQTYPE_LINE 628
#define PQTYPE_FLOAT4 700
#define PQTYPE_FLOAT8 701
#define PQTYPE_UNKNOWN 705
#define PQTYPE_CIRCLE 718
#define PQTYPE_MONEY 790
#define PQTYPE_MACADDR 829
#define PQTYPE_INET 869
#define PQTYPE_CIDR 650
#define PQTYPE_MACADDR8 774
#define PQTYPE_ACLITEM 1033
#define PQTYPE_BPCHAR 1042
#define PQTYPE_VARCHAR 1043
#define PQTYPE_DATE 1082
#define PQTYPE_TIME 1083
#define PQTYPE_TIMESTAMP 1114
#define PQTYPE_TIMESTAMPTZ 1184
#define PQTYPE_INTERVAL 1186
#define PQTYPE_TIMETZ 1266
#define PQTYPE_BIT 1560
#define PQTYPE_VARBIT 1562
#define PQTYPE_NUMERIC 1700
#define PQTYPE_REFCURSOR 1790
#define PQTYPE_REGPROCEDURE 2202
#define PQTYPE_REGOPER 2203
#define PQTYPE_REGOPERATOR 2204
#define PQTYPE_REGCLASS 2205
#define PQTYPE_REGTYPE 2206
#define PQTYPE_REGROLE 4096
#define PQTYPE_REGNAMESPACE 4089
#define PQTYPE_UUID 2950
#define PQTYPE_PG_LSN 3220
#define PQTYPE_TSVECTOR 3614
#define PQTYPE_GTSVECTOR 3642
#define PQTYPE_TSQUERY 3615
#define PQTYPE_REGCONFIG 3734
#define PQTYPE_REGDICTIONARY 3769
#define PQTYPE_JSONB 3802
#define PQTYPE_JSONPATH 4072
#define PQTYPE_TXID_SNAPSHOT 2970
#define PQTYPE_INT4RANGE 3904
#define PQTYPE_NUMRANGE 3906
#define PQTYPE_TSRANGE 3908
#define PQTYPE_TSTZRANGE 3910
#define PQTYPE_DATERANGE 3912
#define PQTYPE_INT8RANGE 3926
#define PQTYPE_RECORD 2249
#define PQTYPE__RECORD 2287
#define PQTYPE_CSTRING 2275
#define PQTYPE_ANY 2276
#define PQTYPE_ANYARRAY 2277
#define PQTYPE_VOID 2278
#define PQTYPE_TRIGGER 2279
#define PQTYPE_EVENT_TRIGGER 3838
#define PQTYPE_LANGUAGE_HANDLER 2280
#define PQTYPE_INTERNAL 2281
#define PQTYPE_OPAQUE 2282
#define PQTYPE_ANYELEMENT 2283
#define PQTYPE_ANYNONARRAY 2776
#define PQTYPE_ANYENUM 3500
#define PQTYPE_FDW_HANDLER 3115
#define PQTYPE_INDEX_AM_HANDLER 325
#define PQTYPE_TSM_HANDLER 3310
#define PQTYPE_TABLE_AM_HANDLER 269
#define PQTYPE_ANYRANGE 3831

#endif /* ndef KNO_PQPRIMS_H */
