(use-module '{optimize reflection})
(config! 'cachelevel 2)
(define default-dir (get-component "english/compiled/"))
(load "english.scm")
(optimize-compilation)
(optimize-arcs)
(define (main (dir #f))
  (write-lexdata (or dir default-dir) #t)
  (commit))
