#!/bin/sh
PKGNAME=${1:-kno};
CODENAME=${2:-debian};
BRANCH=$3;
STATUS=${4:-stable};
URGENCY=${5:-medium};
get_git_branch() {
    branch=$(git branch | \
		 grep "^ *[*-+0123456789][0123456789]*" | \
		 sed -e 's/^ *[*-+0123456789][0123456789]* *//')
    if [ -z $branch ]; then return 1; fi
    echo $branch;
    return 0;
}
get_git_version() {
    version=$(git describe | \
		  sed -e "s/-g[0123456789ABCDEFabcdef]*$//" | \
		  sed -e "s/^${PKGNAME}-//")
    if [ -z $version ]; then return 1; fi
    echo $version;
    return 0;
}
DATE=`date -R`;
gitid=$(git describe);
version=$(get_git_version);
if [ -z ${BRANCH} ] || [ ${BRANCH} = "current" ]; then
    BRANCH=$(get_git_branch);
fi;
if [ -z "${STATUS}" ] || 
   [ ${STATUS} = "stable" ] || 
   [ ${STATUS} = "default" ]; then
    STATUS=
else
    STATUS="-${STATUS}";
fi;
if [ -z "${BRANCH}" ] || \
   [ ${BRANCH} = "trunk" ] || \
   [ ${BRANCH} = "master" ] || \
   [ ${BRANCH} = "default" ]; then
    DBRANCH=
else
    DBRANCH="-${BRANCH}";
fi;
echo ${PKGNAME} \(${version}-${CODENAME}${DBRANCH}\) ${CODENAME}${DBRANCH}${STATUS}\; urgency=${URGENCY}
echo
if [ -z ${DBRANCH} ]; then
    echo "  * ${gitid} point release of ${PKGNAME} for ${CODENAME} (${STATUS})"
else
    echo "  * ${gitid} point release of ${PKGNAME} (branch '${BRANCH}') for ${CODENAME} (${STATUS})"
fi;
echo
echo " -- Repository Manager <repoman@beingmeta.com>  ${DATE}"
echo
cat -
