cd $2
wget $1/absfreq.table
wget $1/analytics.index
wget $1/brico.db
wget $1/brico.pool
wget $1/core.index
wget $1/dtermcache.index
wget $1/english.index
wget $1/enplus.index
wget $1/entails.index
wget $1/latlong.index
wget $1/lattice.index
wget $1/links.index
wget $1/misc.index
wget $1/names.pool
wget $1/parts.index
wget $1/places.pool
wget $1/refs.index
wget $1/slots.index
wget $1/wordforms.index
wget $1/xbrico.pool
wget $1/xplus.index
wget $1/xwords.index
