;;; -*- Mode: Scheme; character-encoding: utf-8; -*-
;;; Copyright (C) 2005-2009 beingmeta, inc.  All rights reserved.

(in-module 'knowlets/usebrico)

;;; Using brico from knowlets, especially for importing information
(define id "$Id$")
(define revision "$Revision: 4048 $")


(use-module '{texttools knowlets brico})
(use-module '{brico/lookup brico/dterms brico/analytics})

(module-export! '{brico->kno kno/usebrico})
(module-export! '{kno/copy-brico-terms! kno/copy-brico-links!})

;;;; Resolving references

(define serial 0)

(define (get-unique-id base knowlet)
  (let ((dterms (knowlet-dterms knowlet)))
    (do ((i 1 (1+ i)))
	((fail? (get dterms (stringout base "(" i ")")))
	 (stringout base "(" i ")")))))

(define (brico->kno bf knowlet (create #f))
  (try (find-frames knowlet:indices 'oid bf)
       (find-frames knowlet:indices
	 'oid bf 'knowlet (knowlet-oid knowlet))
       (tryif create
	 (let* ((language (knowlet-language knowlet))
		(langframe (get language-map language))
		(dterm (pick-one (get-dterm bf langframe)))
		(index (knowlet-index knowlet))
		(kf (kno/dterm
		     (try (or dterm {})
			  (get-unique-id (get-norm bf language)
					 knowlet))
		     knowlet)))
	   (when (ambiguous? bf)
	     (iadd! kf 'dterms (get-dterm bf langframe) index))
	   (unless (eq? language 'en)
	     (iadd! kf 'dterms (cons 'en (get-dterm bf @?en)) index))
	   (when (fail? dterm)
	     (warning "Can't get DTERM for " bf))
	   (iadd! kf 'oid bf)
	   (store! kf 'gloss
		   (try
		    (tryif (eq? language 'en) (get bf 'gloss))
		    (get-gloss bf langframe)))
	   (iadd! kf 'en (get-norm bf @?en))
	   (iadd! kf language
		  (get bf (get language-map language)))
	   kf))))

(define (brico->kno* bf knowlet (visits (make-hashset)))
  (try (find-frames (knowlet-index knowlet) 'oid bf)
       (?? 'oid bf 'knowlet (knowlet-oid knowlet))
       (let* ((always (get bf @?always)))
	 (hashset-add! visits bf)
	 (brico->kno* (reject always visits) knowlet visits))))

;;; Copying information from brico

(define usebrico-defaults
  '#{en fr es nl pt ja zh sw})

(define (kno/usebrico (kf #f) (bf #f) (slotids usebrico-defaults))
  (when (or kf bf)
    (when (not kf)
      (set! kf (find-frames (knowlet-index default-knowlet)
		 'oid bf)))
    (when (not bf) (set! bf (get kf 'oid)))
    (when (overlaps? slotids 'languages)
      (set+! slotids langids))
    (let* ((knowlet (get knowlets (get kf 'knowlet)))
	   (knolang (knowlet-language knowlet))
	   (languages (intersection slotids langids)))
      (if (and (test bf 'gloss) (eq? knolang 'en) (not (test kf 'gloss)))
	  (store! kf 'gloss (get bf 'gloss)))
      (do-choices (lang languages)
	(let ((bricolang (get language-map lang)))
	  (add! kf lang (get bf bricolang))
	  (if (eq? lang knolang)
	      (add! kf 'norms (get-norm bf bricolang))
	      (add! kf 'norms (cons lang (get-norm bf bricolang))))
	  (when (and (eq? lang knolang) (not (test kf 'gloss)))
	    (store! kf 'gloss (get-single-gloss bf bricolang)))
	  (if (eq? lang knolang)
	      (add! kf 'glosses (get bf (get gloss-map lang)))
	      (add! kf 'glosses
		    (cons lang (get bf (get gloss-map lang)))))
	  (if (eq? lang knolang)
	      (add! kf 'hooks (get bf (get index-map lang)))
	      (add! kf 'hooks
		    (cons lang
			  (get bf (get index-map lang)))))))
      (unless (test bf 'sensecat '{noun.tops verb.tops})
	(let* ((genls (get bf {@?always @?commonly}))
	       (commonly (difference (get bf @?commonly) genls))
	       (sometimes (difference (get bf @?sometimes) genls)))
	  (kno/add! kf 'genls (brico->kno genls knowlet))
	  (kno/add! kf 'commonly (brico->kno commonly knowlet))
	  (kno/add! kf 'sometimes (brico->kno sometimes knowlet))))
      (let* ((never (get bf @?never))
	     (rarely (difference (get bf @?rarely) never))
	     (somenot (difference (get bf @?somenot) never)))
	(kno/add! kf 'never (brico->kno never knowlet))
	(kno/add! kf 'rarely (brico->kno rarely knowlet))
	(kno/add! kf 'somenot (brico->kno somenot knowlet)))
      (when (test bf @?refterms)
	(kno/add! kf 'refs (brico->kno (get bf @?refterms) knowlet)))
      (when (test bf @?sumterms)
	(kno/add! kf 'assocs
		  (brico->kno (get bf @?sumterms) knowlet #t)))
      (when (test bf @?sumterms)
	(kno/add! kf 'defs
		  (brico->kno (get bf @?diffterms) knowlet #t)))
      (when (test bf 'country)
	(kno/add! kf (kno/dterm "country" knowlet)
		  (brico->kno (get bf 'country) knowlet #t)))
      (when (test bf 'region)
	(kno/add! kf (kno/dterm "region" knowlet)
		  (brico->kno (get bf 'region) knowlet #t)))
      (when (test bf @?ingredients)
	(kno/add! kf (kno/dterm "ingredient" knowlet)
		  (brico->kno (get bf @?ingredients) knowlet #t)))
      (when (test bf @?memberof)
	(kno/add! kf (kno/dterm "group" knowlet)
		  (brico->kno (get bf @?memberof) knowlet #t)))
      (when (test bf @?partof)
	(kno/add! kf (kno/dterm "assemblage" knowlet)
		  (brico->kno (get bf @?memberof) knowlet #t)))
      (do-choices (role (pick (pickoids (getkeys bf)) 'sensecat))
	(do-choices (v (pickoids (%get bf role)))
	  (kno/add! kf (brico->kno role knowlet #t)
		    (brico->kno v knowlet #t))))
      kf)))

;;;; Copy BRICO links

(define (kno/copy-brico-terms! bf kf (languages {}) (opts 'glosses))
  (let* ((knowlet (->knowlet kf))
	 (knolang (knowlet-language knowlet))
	 (index (knowlet-index knowlet)))
    (do-choices (language (choice knolang 'en languages))
      (let* ((langframe (get language-map language)))
	(when (overlaps? opts 'dterms)
	  (let ((dterm (pick-one (get-dterm bf langframe))))
	    (if (eq? language knolang)
		(iadd! kf 'dterms dterm index)
		(iadd! kf 'dterms (cons 'en dterm) index))
	    (when (fail? dterm)
	      (warning "Can't get DTERM for " bf " in " language))))
	(iadd! kf 'oid bf)
	(when (and (eq? language knolang) (not (test kf 'gloss)))
	  (store! kf 'gloss
		  (stdspace
		   (try
		    (tryif (eq? language 'en) (get bf 'gloss))
		    (get-gloss bf langframe)))))
	(iadd! kf language (get bf langframe))
	(when (overlaps? opts 'glosses)
	  (add! kf 'glosses
		(cons language (stdspace (get-gloss bf langframe)))))
	kf))))

(define (kno/copy-brico-links! (bf #f) (kf #f) (slotids usebrico-defaults))
  (cond ((knowlet? kf)
	 (do-choices (kf (find-frames (knowlet-index kf) 'has 'oid))
	   (kno/copy-brico-links! kf (get kf 'oid) (qc slotids))))
	((and (not (or kf bf)) default-knowlet)
	 (kno/copy-brico-links! default-knowlet #f (qc slotids)))
	((or kf bf)
	 (when (not kf)
	   (set! kf (find-frames (knowlet-index default-knowlet)
		      'oid bf)))
	 (when (not bf) (set! bf (get kf 'oid)))
	 (kno/copy-brico-terms! bf kf (qc (intersection slotids langids)))
	 (let* ((knowlet (get knowlets (get kf 'knowlet)))
		(index (knowlet-index knowlet)))
	   (unless (test bf 'sensecat '{noun.tops verb.tops})
	     (let* ((genls (get bf {@?always @?commonly}))
		    (commonly (difference (get bf @?commonly) genls))
		    (sometimes (difference (get bf @?sometimes) genls)))
	       (kno/add! kf 'genls (brico->kno genls knowlet))
	       (let ((g* (get* kf 'genls))
		     (ng* (find-frames index 'oid (?? @?specls* bf))))
		 (kno/add! kf 'genls (get-basis (difference ng* g*) 'genls)))
	       (kno/add! kf 'commonly (brico->kno commonly knowlet))
	       (kno/add! kf 'sometimes (brico->kno sometimes knowlet))))
	   (let* ((never (get bf @?never))
		  (rarely (difference (get bf @?rarely) never))
		  (somenot (difference (get bf @?somenot) never)))
	     (kno/add! kf 'never (brico->kno never knowlet))
	     (kno/add! kf 'rarely (brico->kno rarely knowlet))
	     (kno/add! kf 'somenot (brico->kno somenot knowlet)))
	   (let* ((never (get+ bf @?never))
		  (rarely (difference (get+ bf @?rarely) never))
		  (somenot (difference (get+ bf @?somenot) never)))
	     (kno/add! kf 'never (find-frames index 'oid never))
	     (kno/add! kf 'rarely (find-frames index 'oid rarely))
	     (kno/add! kf 'somenot (find-frames index 'oid somenot)))
	   (when (overlaps? slotids 'refs)
	     (when (test bf @?refterms)
	       (kno/add! kf 'refs
			 (find-frames index 'oid (get bf @?refterms)))))
	   (when (test bf @?sumterms)
	     (kno/add! kf 'assocs
		       (find-frames index 'oid (get bf @?sumterms))))
	   (when (test bf @?sumterms)
	     (kno/add! kf 'defs
		       (find-frames index 'oid (get bf @?diffterms))))
	   (when (test bf 'country)
	     (kno/add! kf (kno/dterm "country" knowlet)
		       (brico->kno (get bf 'country) knowlet #t)))
	   (when (test bf 'region)
	     (kno/add! kf (kno/dterm "region" knowlet)
		       (brico->kno (get bf 'region) knowlet #t)))
	   (when (test bf @?ingredients)
	     (kno/add! kf (kno/dterm "ingredient" knowlet)
		       (find-frames index 'oid (get bf @?ingredients))))
	   (when (test bf @?memberof)
	     (kno/add! kf (kno/dterm "group" knowlet)
		       (find-frames index 'oid (get bf @?memberof))))
	   (when (test bf @?partof)
	     (kno/add! kf (kno/dterm "assemblage" knowlet)
		       (find-frames index 'oid (get bf @?partof))))
	   (do-choices (role (pick (pickoids (getkeys bf)) 'sensecat))
	     (do-choices (v (find-frames index
			      'oid (pickoids (%get bf role))))
	       (kno/add! kf (brico->kno role knowlet)
			 (find-frames index 'oid v))))
	   kf))
	(else (fail))))





