Document: framerd
Title: Debian framerd Manual
Author: <insert document author here>
Abstract: This manual describes what framerd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/framerd/framerd.sgml.gz

Format: postscript
Files: /usr/share/doc/framerd/framerd.ps.gz

Format: text
Files: /usr/share/doc/framerd/framerd.text.gz

Format: HTML
Index: /usr/share/doc/framerd/html/index.html
Files: /usr/share/doc/framerd/html/*.html
