(TAGTEST
   "The cereal makers insist that their products are a bargain,\r\nparticularly with discount coupons. Even without them, the\r\nindustry estimates that the average cost of a bowl of cereal,\r\nincluding milk, is about 35'. Yet shoppers who watch their\r\nfamilies gobble up a $5 box of cereal in a couple of sittings\r\nstill consider the cost to be considerable. Ann Rhodes, a mother\r\nwith three children at home in Waterford Township, Michigan,\r\nsays of her family, which can shred seven boxes of cereal\r\nweekly, \"The 14-year-old will eat a whole box if you let him,\r\nand the 11-year-old isn't far behind. It has really gotten\r\nexpensive. Cutting prices would get us to buy more.\""
   '(("the" PLURAL-DETERMINER 0) ("cereal" NOUN-MODIFIER 0)
     ("makers" PLURAL-NOUN 0) ("insist" VERB 0)
     ("that" GLUE 0) ("their" POSSESSIVE-PRONOUN 0)
     ("products" PLURAL-NOUN 0) ("are" BE-VERB 0)
     ("a" SINGULAR-DETERMINER 0) ("bargain" NOUN 0)
     ("," PUNCTUATION 0) ("particularly" PADVERB 1)
     ("with" PREPOSITION 1) ("discount" NOUN-MODIFIER 2)
     ("coupons" PLURAL-NOUN 2) ("." PUNCTUATION 2)
     ("even" PADVERB 3) ("without" PREPOSITION 3)
     ("them" PRONOUN 3) ("," PUNCTUATION 3)
     ("the" SINGULAR-DETERMINER 3) ("industry" NOUN 3)
     ("estimates" VERB 3) ("that" GLUE 3)
     ("the" SINGULAR-DETERMINER 3)
     (("average" "cost") NOUN 3) ("of" PREPOSITION 3)
     ("a" SINGULAR-DETERMINER 3) ("bowl" NOUN 3)
     ("of" PREPOSITION 3) ("cereal" SOLITARY-NOUN 5)
     ("," PUNCTUATION 5) ("including" PREPOSITION 5)
     ("milk" SOLITARY-NOUN 7) ("," PUNCTUATION 7)
     ("is" PLURAL-NOUN 14) ("about" PREPOSITION 14)
     ("35" NUMBER 14) ("'." PUNCTUATION 15)
     ("Yet" CONJUNCTION 16) ("shoppers" PLURAL-NOUN 16)
     ("who" GLUE 16) ("watch" VERB 16)
     ("their" POSSESSIVE-PRONOUN 16)
     ("families" PLURAL-NOUN 16) (("gobble" "up") VERB 16)
     ("a" SINGULAR-DETERMINER 16) ("$5" ADJECTIVE 16)
     ("box" NOUN 16) ("of" PREPOSITION 16)
     ("cereal" SOLITARY-NOUN 18) ("in" PREPOSITION 18)
     (("a" "couple" "of") ADJECTIVE 18)
     ("sittings" PLURAL-NOUN 19) ("still" ADVERB 20)
     ("consider" VERB 20) ("the" SINGULAR-DETERMINER 20)
     ("cost" NOUN 20) ("to" "to" 20)
     ("be" COMPLEMENT-AUX 21)
     ("considerable" COMPLEMENT-ADJECTIVE 21)
     ("." PUNCTUATION 21) ("Ann" PROPER-MODIFIER 21)
     ("Rhodes" PROPER-NAME 21) ("," PUNCTUATION 21)
     ("a" SINGULAR-DETERMINER 21) ("mother" NOUN 21)
     ("with" PREPOSITION 21) ("three" NOUN-MODIFIER 21)
     ("children" PLURAL-NOUN 21) ("at" PREPOSITION 21)
     ("home" SOLITARY-NOUN 23) ("in" PREPOSITION 23)
     ("Waterford" PROPER-MODIFIER 23)
     ("Township" PROPER-NAME 25) ("," PUNCTUATION 25)
     ("Michigan" PROPER-NAME 25) ("," PUNCTUATION 25)
     ("says" VERB 25) ("of" PREPOSITION 25)
     ("her" POSSESSIVE-PRONOUN 25) ("family" NOUN 25)
     ("," PUNCTUATION 25) ("which" GLUE 25)
     ("can" MODAL-AUX 25) ("shred" VERB 26)
     ("seven" NOUN-MODIFIER 26) ("boxes" PLURAL-NOUN 26)
     ("of" PREPOSITION 26) ("cereal" SOLITARY-NOUN 28)
     ("weekly" TIME-WORD 28) ("," "," 28)
     ("\"" PUNCTUATION 29) ("The" SINGULAR-DETERMINER 29)
     ("14-year-old" NOUN 33) ("will" MODAL-AUX 33)
     ("eat" VERB 33) ("a" SINGULAR-DETERMINER 33)
     ("whole" ADJECTIVE 33) ("box" NOUN 33) ("if" GLUE 33)
     ("you" PRONOUN 33) ("let" VERB 33) ("him" PRONOUN 33)
     ("," PUNCTUATION 33) ("and" "and" 33)
     ("the" SINGULAR-DETERMINER 33) ("11-year-old" NOUN 37)
     ("isn't" COMPLEMENT-AUX 38)
     (("far" "behind") COMPLEMENT-ADJECTIVE 38)
     ("." PUNCTUATION 38) ("It" PRONOUN 38)
     ("has" HAVE-AUX 38) ("really" ADVERB 38)
     ("gotten" COMPLEMENT-AUX 38)
     ("expensive" COMPLEMENT-ADJECTIVE 38)
     ("." SENTENCE-END 38) ("Cutting" VERB 38)
     ("prices" PLURAL-NOUN 38) ("would" MODAL-AUX 38)
     ("get" VERB 38) ("us" PRONOUN 38) ("to" "to" 38)
     ("buy" VERB 38) ("more" TRAILING-ADVERB 40)
     (".\"" PUNCTUATION 40)))
(TAGTEST
   "Giuliani took immediate political heat for the response and his\r\npredictably gruff defense of the N.Y.P.D. But the Busch shooting\r\nreflects a chronic problem, one that affects communities\r\nthroughout the country. Increasingly, police action appears to be\r\nthe only action that can be taken with EDPs. \"Law-enforcement\r\nofficers are serving as front-line mental-health workers,\" says\r\nMary Zdanowicz, executive director of the Treatment Advocacy\r\nCenter, based in Virginia. \"But by the time the police intercede,\r\nit's usually too late.\""
   '(("Giuliani" PROPER-NAME 0) ("took" VERB 0)
     ("immediate" ADJECTIVE 0) ("political" ADJECTIVE 0)
     ("heat" SOLITARY-NOUN 2) ("for" PREPOSITION 2)
     ("the" SINGULAR-DETERMINER 2) ("response" NOUN 2)
     ("and" "and" 2) ("his" POSSESSIVE-PRONOUN 2)
     ("predictably" ADVERB 2) ("gruff" ADJECTIVE 2)
     ("defense" NOUN 2) ("of" PREPOSITION 2)
     ("the" SINGULAR-DETERMINER 2)
     ("N.Y.P.D." PROPER-NAME 2) ("but" CONJUNCTION 6)
     ("the" SINGULAR-DETERMINER 6)
     ("Busch" PROPER-MODIFIER 6) ("shooting" NOUN 8)
     ("reflects" VERB 8) ("a" SINGULAR-DETERMINER 8)
     ("chronic" ADJECTIVE 8) ("problem" NOUN 8)
     ("," PUNCTUATION 8) ("one" PRONOUN 9) ("that" GLUE 9)
     ("affects" VERB 9) ("communities" PLURAL-NOUN 9)
     ("throughout" PREPOSITION 9)
     ("the" SINGULAR-DETERMINER 9) ("country" NOUN 9)
     ("." PUNCTUATION 9)
     ("Increasingly" DANGLING-ADVERB 10) ("," "," 10)
     (("police" "action") SOLITARY-NOUN 12)
     ("appears" VERB 13) ("to" "to" 13) ("be" BE-VERB 13)
     ("the" SINGULAR-DETERMINER 13) ("only" ADJECTIVE 14)
     ("action" NOUN 14) ("that" GLUE 14)
     ("can" MODAL-AUX 14) ("be" BE-AUX 14) ("taken" VERB 14)
     ("with" PREPOSITION 14) ("EDPs" PROPER-NAME 14)
     ("." PUNCTUATION 14) ("\"" PUNCTUATION 14)
     ("Law-enforcement" ADJECTIVE 16)
     ("officers" PLURAL-NOUN 16) ("are" BE-AUX 16)
     ("serving" ING-VERB 16) ("as" PREPOSITION 16)
     ("front-line" ADJECTIVE 18)
     ("mental-health" ADJECTIVE 20)
     ("workers" PLURAL-NOUN 20) (",\"" PUNCTUATION 20)
     ("says" VERB 20) ("Mary" PROPER-MODIFIER 20)
     ("Zdanowicz" PROPER-NAME 20) ("," PUNCTUATION 20)
     (("executive" "director") SOLITARY-NOUN 22)
     ("of" PREPOSITION 22) ("the" SINGULAR-DETERMINER 22)
     ("Treatment" PROPER-MODIFIER 22)
     ("Advocacy" PROPER-MODIFIER 22)
     ("Center" PROPER-NAME 22) ("," PUNCTUATION 22)
     ("based" VERB 23) ("in" PREPOSITION 23)
     ("Virginia" PROPER-NAME 23) ("." PUNCTUATION 23)
     ("\"" PUNCTUATION 23) ("but" CONJUNCTION 24)
     ("by" PREPOSITION 24) ("the" SINGULAR-DETERMINER 24)
     ("time" NOUN 24) ("the" SINGULAR-DETERMINER 27)
     ("police" SOLITARY-NOUN 27) ("intercede" VERB 28)
     ("," "," 29) ("it's" COMPLEMENT-AUX 29)
     ("usually" ADVERB 29) ("too" ADVERB 29)
     ("late" COMPLEMENT-ADJECTIVE 29)
     (".\"" PUNCTUATION 29)))
(TAGTEST
   "Where I come from, they call that hush money. But just after New\r\nYear's Day, Stanford told me last week, a reporter from the\r\nEnquirer came to her L.A. home offering \"up to a million\" in\r\nexchange for her story. She says she declined. But as Stanford\r\nnotes, there are plenty of  disgruntled former Rainbow staff\r\nmembers around who \"hate Jesse and want to destroy him\" so much\r\nthey didn't need cash as an incentive to spill what they knew. It\r\nwas Jackson, in his arrogance, who provided them with the\r\nsqualid tale that may bring him down. To appropriate one of\r\nJackson's slogans, his time has gone."
   '(("Where" GLUE 0) ("I" PRONOUN 0) ("come" VERB 0)
     ("from" TRAILING-ADVERB 1) ("," "," 1)
     ("they" PRONOUN 1) ("call" VERB 1)
     ("that" SINGULAR-DETERMINER 2)
     (("hush" "money") NOUN 2) ("." PUNCTUATION 2)
     ("but" CONJUNCTION 3) ("just" PADVERB 5)
     ("after" PREPOSITION 5)
     (("New" "Year's" "Day") PROPER-NAME 5)
     ("," PUNCTUATION 5) ("Stanford" PROPER-NAME 5)
     ("told" VERB 5) ("me" PRONOUN 5)
     (("last" "week") TIME-WORD 5) ("," "," 5)
     ("a" SINGULAR-DETERMINER 5) ("reporter" NOUN 5)
     ("from" PREPOSITION 5) ("the" SINGULAR-DETERMINER 5)
     ("Enquirer" SOLITARY-NOUN 5) ("came" VERB 5)
     ("to" PREPOSITION 5) ("her" POSSESSIVE-PRONOUN 5)
     ("L.A." PROPER-MODIFIER 5) ("home" NOUN 5)
     ("offering" VERB 5) ("\"" PUNCTUATION 5)
     (("up" "to") PREPOSITION 5)
     ("a" SINGULAR-DETERMINER 5) ("million" NOUN 5)
     ("\"" PUNCTUATION 5) ("in" PREPOSITION 5)
     ("exchange" SOLITARY-NOUN 8) ("for" PREPOSITION 8)
     ("her" POSSESSIVE-PRONOUN 8) ("story" NOUN 8)
     ("." PUNCTUATION 8) ("She" PRONOUN 8) ("says" VERB 8)
     ("she" PRONOUN 8) ("declined" VERB 8)
     ("." SENTENCE-END 8) ("but" CONJUNCTION 9)
     ("as" PREPOSITION 9) ("Stanford" PROPER-NAME 9)
     ("notes" VERB 10) ("," "," 10) ("there" PRONOUN 11)
     ("are" BE-VERB 11) ("plenty" SOLITARY-NOUN 13)
     ("of" PREPOSITION 13) ("disgruntled" ADJECTIVE 14)
     ("former" ADJECTIVE 14) ("Rainbow" PROPER-MODIFIER 14)
     ("staff" NOUN-MODIFIER 14) ("members" PLURAL-NOUN 14)
     ("around" PREPOSITION 14) ("who" PRONOUN 14)
     ("\"" PUNCTUATION 14) ("hate" VERB 14)
     ("Jesse" PROPER-NAME 14) ("and" "and" 14)
     ("want" VERB 15) ("to" "to" 15) ("destroy" VERB 15)
     ("him" PRONOUN 15) ("\"" PUNCTUATION 15)
     (("so" "much") DANGLING-ADJECTIVE 17)
     ("they" PRONOUN 17) ("didn't" MODAL-AUX 17)
     ("need" VERB 17) ("cash" SOLITARY-NOUN 19)
     ("as" PREPOSITION 19) ("an" SINGULAR-DETERMINER 19)
     ("incentive" NOUN 19) ("to" "to" 19) ("spill" VERB 19)
     ("what" GLUE 19) ("they" PRONOUN 19) ("knew" VERB 19)
     ("." PUNCTUATION 19) ("It" PRONOUN 19)
     ("was" BE-VERB 19) ("Jackson" PROPER-NAME 19)
     ("," PUNCTUATION 19) ("in" PREPOSITION 19)
     ("his" POSSESSIVE-PRONOUN 19) ("arrogance" NOUN 19)
     ("," PUNCTUATION 19) ("who" GLUE 19)
     ("provided" VERB 19) ("them" PRONOUN 19)
     ("with" PREPOSITION 19) ("the" SINGULAR-DETERMINER 19)
     ("squalid" ADJECTIVE 19) ("tale" NOUN 19)
     ("that" GLUE 19) ("may" MODAL-AUX 19) ("bring" VERB 20)
     ("him" PRONOUN 20) ("down" DANGLING-ADVERB 23)
     ("." SENTENCE-END 23) ("to" "to" 23)
     ("appropriate" VERB 24) ("one" PRONOUN 25)
     ("of" PREPOSITION 25) ("Jackson's" POSSESSIVE 27)
     ("slogans" PLURAL-NOUN 27) ("," PUNCTUATION 27)
     ("his" POSSESSIVE-PRONOUN 27) ("time" NOUN 27)
     ("has" HAVE-AUX 27) ("gone" VERB 28)
     ("." PUNCTUATION 28)))
(TAGTEST
   "By week's end, a sense of panic had crept from the 24-hr.\r\n\"Terror in the Rockies\" broadcasts into the statehouses as well.\r\nSome were more panicked than others: California Governor Gray\r\nDavis spoke of the importance of guidance counselors, but,\r\nreflecting the differences in the men and their states, Virginia\r\nGovernor Jim Gilmore ordered superintendents to report any\r\npotentially dangerous student to police immediately. School\r\ndistricts are alarmed by the governmental consternation. Just\r\nlast week, 150 calls were directed to Russ Ebersole, who runs a\r\nsmall but suddenly lucrative Bethesda, Md., firm that takes $500\r\nfrom schools to bring in Labrador retrievers that sniff out\r\nbombs and gunpowder. Even so, after the worst school massacre in\r\nthis country's history, there must be something we can do. Right?"
   '(("By" PREPOSITION 0) ("week's" POSSESSIVE 0)
     ("end" NOUN 0) ("," PUNCTUATION 0)
     ("a" SINGULAR-DETERMINER 0) ("sense" NOUN 0)
     ("of" PREPOSITION 0) ("panic" SOLITARY-NOUN 2)
     ("had" HAVE-AUX 2) ("crept" VERB 2)
     ("from" PREPOSITION 2) ("the" SINGULAR-DETERMINER 2)
     ("24-hr" NOUN 6) ("." PUNCTUATION 6)
     ("\"" PUNCTUATION 6) ("Terror" SOLITARY-NOUN 6)
     ("in" PREPOSITION 6) ("the" SINGULAR-DETERMINER 6)
     ("Rockies" PROPER-NAME 6) ("\"" PUNCTUATION 6)
     ("broadcasts" VERB 6) ("into" PREPOSITION 6)
     ("the" SINGULAR-DETERMINER 6)
     ("statehouses" PLURAL-NOUN 6)
     (("as" "well") DANGLING-ADVERB 7) ("." SENTENCE-END 7)
     ("Some" PRONOUN 8) ("were" COMPLEMENT-AUX 8)
     ("more" ADVERB 9) ("panicked" COMPLEMENT-ADJECTIVE 9)
     ("than" PREPOSITION 9) ("others" PLURAL-NOUN 13)
     (":" PUNCTUATION 13) ("California" PROPER-MODIFIER 15)
     ("Governor" PROPER-MODIFIER 15)
     ("Gray" PROPER-MODIFIER 15) ("Davis" PROPER-NAME 15)
     (("spoke" "of") VERB 15)
     ("the" SINGULAR-DETERMINER 15) ("importance" NOUN 15)
     ("of" PREPOSITION 15) ("guidance" NOUN-MODIFIER 15)
     ("counselors" PLURAL-NOUN 15) ("," PUNCTUATION 15)
     ("but" ANYTHING 35) ("," "," 35) ("reflecting" VERB 35)
     ("the" SINGULAR-DETERMINER 35)
     ("differences" PLURAL-NOUN 35) ("in" PREPOSITION 35)
     ("the" SINGULAR-DETERMINER 35) ("men" PLURAL-NOUN 35)
     ("and" "and" 35) ("their" POSSESSIVE-PRONOUN 35)
     ("states" PLURAL-NOUN 35) ("," PUNCTUATION 35)
     ("Virginia" PROPER-MODIFIER 37)
     ("Governor" PROPER-MODIFIER 37)
     ("Jim" PROPER-MODIFIER 37) ("Gilmore" PROPER-NAME 37)
     ("ordered" VERB 38) ("superintendents" PLURAL-NOUN 38)
     ("to" "to" 38) ("report" VERB 39) ("any" ANYTHING 62)
     ("potentially" ADVERB 62) ("dangerous" ADJECTIVE 62)
     ("student" SOLITARY-NOUN 64) ("to" PREPOSITION 64)
     ("police" SOLITARY-NOUN 64)
     ("immediately" TIME-WORD 64) ("." SENTENCE-END 64)
     ("School" NOUN-MODIFIER 64)
     ("districts" PLURAL-NOUN 64) ("are" COMPLEMENT-AUX 64)
     ("alarmed" COMPLEMENT-ADJECTIVE 64)
     ("by" PREPOSITION 64) ("the" SINGULAR-DETERMINER 64)
     ("governmental" ADJECTIVE 64)
     ("consternation" NOUN 64) ("." PUNCTUATION 64)
     ("Just" PROPER-NAME 64) (("last" "week") TIME-WORD 64)
     ("," "," 64) ("150" ADJECTIVE 64)
     ("calls" PLURAL-NOUN 65) ("were" BE-AUX 65)
     ("directed" VERB 65) ("to" PREPOSITION 65)
     ("Russ" PROPER-MODIFIER 65)
     ("Ebersole" PROPER-NAME 65) ("," PUNCTUATION 65)
     ("who" GLUE 65) ("runs" VERB 65)
     ("a" SINGULAR-DETERMINER 65) ("small" ADJECTIVE 65)
     ("but" CONJUNCTION 65) ("suddenly" ADVERB 65)
     ("lucrative" ADJECTIVE 65) ("Bethesda" PROPER-NAME 65)
     ("," PUNCTUATION 65) ("Md" PROPER-NAME 65)
     (".," PUNCTUATION 65) ("firm" VERB 66) ("that" GLUE 66)
     ("takes" VERB 66) ("$500" NUMBER 66)
     ("from" PREPOSITION 66) ("schools" PLURAL-NOUN 66)
     ("to" "to" 66) ("bring" VERB 67) ("in" PREPOSITION 69)
     ("Labrador" PROPER-MODIFIER 69)
     ("retrievers" PLURAL-NOUN 69) ("that" GLUE 69)
     ("sniff" VERB 69) ("out" PREPOSITION 69)
     ("bombs" PLURAL-NOUN 70) ("and" "and" 70)
     ("gunpowder" SOLITARY-NOUN 72) ("." PUNCTUATION 72)
     (("even" "so") DANGLING-ADVERB 73) ("," "," 73)
     ("after" PREPOSITION 73)
     ("the" SINGULAR-DETERMINER 73) ("worst" ADJECTIVE 73)
     ("school" NOUN-MODIFIER 73) ("massacre" NOUN 73)
     ("in" PREPOSITION 73) ("this" PRONOUN 73)
     ("country's" POSSESSIVE 76) ("history" NOUN 76)
     ("," PUNCTUATION 76) ("there" ADVERB 77)
     ("must" AUX 78) ("be" BE-VERB 78)
     ("something" PRONOUN 78) ("we" PRONOUN 81)
     ("can" MODAL-AUX 81) ("do" VERB 82)
     ("." PUNCTUATION 82) ("Right" SOLITARY-NOUN 83)
     ("?" PUNCTUATION 83)))
(TAGTEST "Other Voices"
   '(("Other" PROPER-MODIFIER 0) ("Voices" PROPER-NAME 0)))
(TAGTEST
   "Without preamble, the three-piece band cuts loose. In the\r\nspotlight, the lanky singer flails furious rhythms on his\r\nguitar, every now and then breaking a string. In a pivoting\r\nstance, his hips swing sensuously from side to side and his\r\nentire body takes on a frantic quiver, as if he had swallowed a\r\njackhammer. Full-cut hair tumbles over his forehead, and\r\nsideburns frame his petulant, full-lipped face. His style is\r\npartly hillbilly, partly socking rock 'n' roll. His loud\r\nbaritone goes raw and whining in the high notes, but down low it\r\nis rich and round. As he throws himself into one of his\r\nspecialties--Heartbreak Hotel, Blue Suede Shoes or Long Tall\r\nSally--his throat seems full of desperate aspirates (\"Hi want\r\nyou, hi need you, hi luh-huh-huh-huv yew-hew\") or hiccuping\r\nglottis strokes, and his diction is poor. But his movements\r\nsuggest, in a word, sex."
   '(("Without" PREPOSITION 0) ("preamble" SOLITARY-NOUN 2)
     ("," PUNCTUATION 2) ("the" SINGULAR-DETERMINER 2)
     ("three-piece" ADJECTIVE 2) ("band" NOUN 2)
     ("cuts" VERB 2) ("loose" TRAILING-ADVERB 4)
     ("." PUNCTUATION 4) ("in" PREPOSITION 4)
     ("the" SINGULAR-DETERMINER 4) ("spotlight" NOUN 4)
     ("," PUNCTUATION 4) ("the" SINGULAR-DETERMINER 4)
     ("lanky" ADJECTIVE 4) ("singer" NOUN 4)
     ("flails" VERB 5) ("furious" ADJECTIVE 5)
     ("rhythms" PLURAL-NOUN 5) ("on" PREPOSITION 5)
     ("his" POSSESSIVE-PRONOUN 5) ("guitar" NOUN 5)
     ("," PUNCTUATION 5) ("every" ANYTHING 25)
     (("now" "and" "then") ADVERB 25)
     ("breaking" ING-VERB 25) ("a" SINGULAR-DETERMINER 25)
     ("string" NOUN 26) ("." PUNCTUATION 26)
     ("in" PREPOSITION 26) ("a" SINGULAR-DETERMINER 26)
     ("pivoting" NOUN-MODIFIER 27) ("stance" NOUN 27)
     ("," PUNCTUATION 27) ("his" POSSESSIVE-PRONOUN 27)
     ("hips" PLURAL-NOUN 27) ("swing" VERB 28)
     ("sensuously" PADVERB 29) ("from" PREPOSITION 29)
     ("side" NOUN 29) ("to" "to" 29) ("side" VERB 30)
     ("and" "and" 30) ("his" POSSESSIVE-PRONOUN 30)
     ("entire" ADJECTIVE 30) ("body" NOUN 30)
     (("takes" "on") VERB 30) ("a" SINGULAR-DETERMINER 30)
     ("frantic" ADJECTIVE 30) ("quiver" NOUN 31)
     ("," PUNCTUATION 31) ("as" DANGLING-ADVERB 34)
     ("if" GLUE 34) ("he" PRONOUN 34) ("had" HAVE-AUX 34)
     ("swallowed" VERB 34) ("a" SINGULAR-DETERMINER 34)
     ("jackhammer" NOUN 34) ("." PUNCTUATION 34)
     ("Full-cut" ADJECTIVE 34) ("hair" NOUN-MODIFIER 34)
     ("tumbles" PLURAL-NOUN 35) ("over" PREPOSITION 35)
     ("his" POSSESSIVE-PRONOUN 35) ("forehead" NOUN 35)
     ("," PUNCTUATION 35) ("and" "and" 35)
     ("sideburns" PLURAL-NOUN 35) ("frame" VERB 36)
     ("his" POSSESSIVE-PRONOUN 36)
     ("petulant" ADJECTIVE 36) ("," "," 36)
     ("full-lipped" ADJECTIVE 38) ("face" NOUN 38)
     ("." PUNCTUATION 38) ("His" POSSESSIVE-PRONOUN 38)
     ("style" NOUN 38) ("is" COMPLEMENT-AUX 38)
     ("partly" ADVERB 38)
     ("hillbilly" COMPLEMENT-ADJECTIVE 39) ("," "," 40)
     ("partly" ADVERB 40) ("socking" ING-VERB 40)
     ("rock" SOLITARY-NOUN 42) ("'" PUNCTUATION 42)
     ("n" SOLITARY-NOUN 44) ("'" PUNCTUATION 44)
     ("roll" VERB 44) ("." PUNCTUATION 44)
     ("His" POSSESSIVE-PRONOUN 44) ("loud" ADJECTIVE 44)
     ("baritone" NOUN 44) ("goes" COMPLEMENT-AUX 44)
     ("raw" COMPLEMENT-ADJECTIVE 44) ("and" "and" 44)
     ("whining" ING-VERB 44) ("in" PREPOSITION 44)
     ("the" PLURAL-DETERMINER 44) ("high" ADJECTIVE 44)
     ("notes" PLURAL-NOUN 44) ("," PUNCTUATION 44)
     ("but" CONJUNCTION 45) ("down" ADVERB 47)
     ("low" VERB 48) ("it" PRONOUN 48)
     ("is" COMPLEMENT-AUX 48)
     ("rich" COMPLEMENT-ADJECTIVE 48)
     ("and" CONJUNCTION 48)
     ("round" COMPLEMENT-ADJECTIVE 48) ("." PUNCTUATION 48)
     ("as" PREPOSITION 48) ("he" PRONOUN 48)
     ("throws" VERB 48) ("himself" PRONOUN 48)
     ("into" PREPOSITION 48) ("one" PRONOUN 49)
     ("of" PREPOSITION 49) ("his" POSSESSIVE-PRONOUN 49)
     ("specialties" PLURAL-NOUN 49) ("--" PUNCTUATION 49)
     ("Heartbreak" NOUN-MODIFIER 49)
     ("Hotel" SOLITARY-NOUN 49) ("," PUNCTUATION 49)
     ("Blue" PROPER-MODIFIER 49)
     ("Suede" PROPER-MODIFIER 49) ("Shoes" PROPER-NAME 51)
     ("or" "or" 51) ("Long" PROPER-MODIFIER 51)
     ("Tall" PROPER-MODIFIER 51) ("Sally" PROPER-NAME 51)
     ("--" PUNCTUATION 51) ("his" POSSESSIVE-PRONOUN 51)
     ("throat" NOUN 51) ("seems" COMPLEMENT-AUX 51)
     ("full" COMPLEMENT-ADJECTIVE 51) ("of" PREPOSITION 51)
     ("desperate" ADJECTIVE 51)
     ("aspirates" PLURAL-NOUN 52) ("(\"" PUNCTUATION 52)
     ("Hi" PROPER-NAME 52) ("want" VERB 53)
     ("you" PRONOUN 53) ("," PUNCTUATION 53)
     ("hi" SOLITARY-NOUN 56) ("need" VERB 56)
     ("you" PRONOUN 56) ("," PUNCTUATION 56)
     ("hi" SOLITARY-NOUN 59)
     ("luh-huh-huh-huv" ADJECTIVE 66) ("yew-hew" NOUN 70)
     ("\")" PUNCTUATION 70) ("or" "or" 70)
     ("hiccuping" ING-VERB 70) ("glottis" NOUN-MODIFIER 70)
     ("strokes" PLURAL-NOUN 70) ("," PUNCTUATION 70)
     ("and" "and" 70) ("his" POSSESSIVE-PRONOUN 70)
     ("diction" NOUN 70) ("is" COMPLEMENT-AUX 70)
     ("poor" COMPLEMENT-ADJECTIVE 70) ("." SENTENCE-END 70)
     ("but" CONJUNCTION 71) ("his" POSSESSIVE-PRONOUN 71)
     ("movements" PLURAL-NOUN 71) ("suggest" VERB 72)
     ("," "," 72) ("in" PREPOSITION 72)
     ("a" SINGULAR-DETERMINER 72) ("word" NOUN 72)
     ("," PUNCTUATION 72) ("sex" VERB 73)
     ("." PUNCTUATION 73)))
(TAGTEST
   "At the same time, it's worth recognizing that the efforts of the\r\nU.S. government and others to get people to live in multinational\r\nand multiethnic communities are more often than not exercises in\r\nfutility. Instead, it is often wise to accommodate those pushing\r\nfor ethnic separation, segregation and homogenization--even if\r\nthat means partitioning entire nations to reduce violence."
   '(("At" PROPER-NAME 2) ("the" SINGULAR-DETERMINER 5)
     ("same" ADJECTIVE 5) ("time" NOUN 5)
     ("," PUNCTUATION 5) ("it's" COMPLEMENT-AUX 5)
     ("worth" COMPLEMENT-ADJECTIVE 5)
     ("recognizing" ING-VERB 8) ("that" GLUE 8)
     ("the" SINGULAR-DETERMINER 8)
     ("efforts" PLURAL-NOUN 8) ("of" PREPOSITION 8)
     ("the" SINGULAR-DETERMINER 8)
     ("U.S." PROPER-MODIFIER 8) ("government" NOUN 8)
     ("and" "and" 8) ("others" PLURAL-NOUN 12)
     ("to" "to" 12) ("get" VERB 12)
     ("people" SOLITARY-NOUN 14) ("to" "to" 14)
     ("live" VERB 14) ("in" PREPOSITION 14)
     ("multinational" ADJECTIVE 14) ("and" CONJUNCTION 14)
     ("multiethnic" ADJECTIVE 18)
     ("communities" PLURAL-NOUN 18) ("are" BE-VERB 18)
     ("more" SOLITARY-NOUN 21) ("often" DANGLING-ADVERB 22)
     ("than" CONJUNCTION 23) ("not" NEGATOR 23)
     ("exercises" VERB 23) ("in" PREPOSITION 23)
     ("futility" SOLITARY-NOUN 25) ("." PUNCTUATION 25)
     ("Instead" DANGLING-ADVERB 26) ("," "," 26)
     ("it" PRONOUN 26) ("is" COMPLEMENT-AUX 26)
     ("often" ADVERB 26) ("wise" COMPLEMENT-ADJECTIVE 26)
     ("to" "to" 26) ("accommodate" VERB 27)
     ("those" PRONOUN 27) ("pushing" VERB 27)
     ("for" PREPOSITION 27) ("ethnic" ADJECTIVE 27)
     ("separation" SOLITARY-NOUN 29) ("," PUNCTUATION 29)
     ("segregation" SOLITARY-NOUN 31) ("and" "and" 31)
     ("homogenization" SOLITARY-NOUN 33)
     ("--" PUNCTUATION 33) ("even" DANGLING-ADVERB 34)
     ("if" GLUE 34) ("that" GLUE 34) ("means" VERB 34)
     ("partitioning" ING-VERB 34) ("entire" ADJECTIVE 34)
     ("nations" PLURAL-NOUN 34) ("to" "to" 34)
     ("reduce" VERB 34) ("violence" SOLITARY-NOUN 36)
     ("." PUNCTUATION 36)))
(TAGTEST
   "\r\n\r\nRADICAL CHIC\r\nDjindjic has a Ph.D. in philosophy. During Tito's iron rule, his\r\nstudent activism led to his arrest\r\n\r\nSHARPLY DRESSED \r\nTall and elegantly attired, Djindjic looks different from the\r\ngauche, lumpy apparatchiks who surrounded Slobo \r\n\r\nDICK MORRIS?\r\nDjindjic has a sharp political mind. Insiders credit him with\r\nfine-tuning the street strategy that dumped Milosevic \r\n\r\nCLEAR VIEW\r\nDjindjic says he wants Serbia to have a transparent political\r\nsystem--a necessity for joining Europe's economy\r\n\r\n\r\n"
   '(("|" SENTENCE-END 0) ("RADICAL" PROPER-MODIFIER 0)
     ("CHIC" PROPER-MODIFIER 0) ("Djindjic" PROPER-NAME 0)
     ("has" VERB 1) ("a" SINGULAR-DETERMINER 1)
     ("Ph.D." PROPER-NAME 1) ("in" PREPOSITION 1)
     ("philosophy" SOLITARY-NOUN 3) ("." PUNCTUATION 3)
     ("During" PREPOSITION 3) ("Tito's" POSSESSIVE 5)
     ("iron" NOUN-MODIFIER 5) ("rule" NOUN 5)
     ("," PUNCTUATION 5) ("his" POSSESSIVE-PRONOUN 5)
     ("student" NOUN-MODIFIER 5) ("activism" NOUN 5)
     ("led" VERB 5) ("to" PREPOSITION 5)
     ("his" POSSESSIVE-PRONOUN 5) ("arrest" NOUN 6)
     ("|" PUNCTUATION 6) ("SHARPLY" ADVERB 6)
     ("DRESSED" VERB 6) ("Tall" PROPER-NAME 8)
     ("and" "and" 8) ("elegantly" ADVERB 8)
     ("attired" VERB 9) ("," "," 9)
     ("Djindjic" PROPER-NAME 9) ("looks" COMPLEMENT-AUX 10)
     ("different" COMPLEMENT-ADJECTIVE 10)
     ("from" PREPOSITION 10) ("the" PLURAL-DETERMINER 10)
     ("gauche" ADJECTIVE 10) ("," "," 10)
     ("lumpy" ADJECTIVE 10) ("apparatchiks" PLURAL-NOUN 10)
     ("who" GLUE 10) ("surrounded" VERB 11)
     ("Slobo" PROPER-NAME 11) ("|" PUNCTUATION 11)
     ("DICK" PROPER-MODIFIER 11) ("MORRIS" PROPER-NAME 11)
     ("?" PUNCTUATION 11) ("Djindjic" PROPER-NAME 11)
     ("has" VERB 12) ("a" SINGULAR-DETERMINER 12)
     ("sharp" ADJECTIVE 12) ("political" ADJECTIVE 12)
     ("mind" NOUN 12) ("." PUNCTUATION 12)
     ("Insiders" PROPER-NAME 12) ("credit" VERB 13)
     ("him" PRONOUN 13) ("with" PREPOSITION 13)
     ("fine-tuning" ING-VERB 13)
     ("the" SINGULAR-DETERMINER 13)
     ("street" NOUN-MODIFIER 13) ("strategy" NOUN 13)
     ("that" GLUE 13) ("dumped" VERB 13)
     ("Milosevic" PROPER-NAME 13) ("|" PUNCTUATION 13)
     ("CLEAR" PROPER-MODIFIER 13)
     ("VIEW" PROPER-MODIFIER 13)
     ("Djindjic" PROPER-NAME 13) ("says" VERB 13)
     ("he" PRONOUN 13) ("wants" VERB 14)
     ("Serbia" PROPER-NAME 14) ("to" "to" 14)
     ("have" VERB 15) ("a" SINGULAR-DETERMINER 15)
     ("transparent" ADJECTIVE 15)
     (("political" "system") NOUN 15) ("--" PUNCTUATION 15)
     ("a" SINGULAR-DETERMINER 15) ("necessity" NOUN 15)
     ("for" PREPOSITION 15) ("joining" ING-VERB 15)
     ("Europe's" POSSESSIVE 17) ("economy" NOUN 17)
     ("|" PUNCTUATION 17)))
