libpng:
	git clone git://git.code.sf.net/p/libpng/code libpng
libqrencode:
	git clone https://github.com/fukuchi/libqrencode.git libqrencode
libexif:
	cvs -d:pserver:anonymous@libexif.cvs.sourceforge.net:/cvsroot/libexif login
	cvs -z3 -d:pserver:anonymous@libexif.cvs.sourceforge.net:/cvsroot/libexif co -P libexif

