#!/bin/sh
FLEXFILE=$1
TAILTHRESH=${2:-1}
BACKUP_ARG=$3
FLEXBASE=$(basename ${FLEXFILE} .flexindex)
#FLEXBASE=${FLEXFILE/.flexindex/}
SPLITINDEX_CMD=${SPLITINDEX_CMD:-knodb splitindex}
export BACKUP
if [ ! -z "${BACKUP_ARG}" ]; then
    BACKUP="${BACKUP_ARG}";
elif [ ! -z "${BACKUP}" ]; then
    :;
elif [ -d backup ]; then
    BACKUP=./backup/;
else BACKUP=.split;
fi;
echo FLEXBASE=${FLEXBASE}
backup_partition( ) {
    local partition=$1;
    if [ -d ${BACKUP} ]; then
	mv ${partition} ${BACKUP};
    elif [ "${BACKUP}" = "remove" ]; then
	rm ${partition};
    else
	mv ${partition} ${partition}${BACKUP}
    fi;
}
for partition in ${FLEXBASE}.*.index; do 
    ${SPLITINDEX_CMD} ${partition} ${FLEXBASE}.index ${FLEXBASE}_tail.flexindex ${TAILTHRESH} && backup_partition ${partition}
done
