#!/bin/sh
FLEXFILE=$1
TAILTHRESH=${2:-1}
SPLITINDEX_CMD=${SPLITINDEX_CMD:-splitindex}

FLEXBASE=${FLEXFILE/.flexpool//}

for partition in ${FLEXBASE}.*.index; do 
    ${SPLITINDEX_CMD} ${partition} ${FLEXBASE}.index ${FLEXBASE}_tail.flexindex ${TAILTHRESH}};
done
    
