#!/bin/sh

if [ -f runenv.sh ]; then
   . runenv.sh;
elif [ -f dbg/runenv.sh ]; then
    echo "Using dbg/runenv.sh";
   . dbg/runenv.sh;
elif [ -f ../dbg/runenv.sh ]; then
    echo "Using ../dbg/runenv.sh";
   . ../dbg/runenv.sh;
else
    echo "Can't find runenv.sh!";
    exit;
fi;
EXEC_PROG=
case $1 in
    *.scm)
	EXEC_PROG=./knox
esac

MEMCHECKING=yes ASAN_SYMBOLIZER_PATH= ASAN_OPTIONS=malloc_context_size=20 LSAN_OPTIONS=report_objects=1  ${EXEC_PROG} $* DLOAD:TRACE=yes
