#!/bin/sh

if [ -f runenv.sh ]; then
   . runenv.sh;
elif [ -f dbg/runenv.sh ]; then
    echo "Using dbg/runenv.sh";
   . dbg/runenv.sh;
elif [ -f ../dbg/runenv.sh ]; then
    echo "Using ../dbg/runenv.sh";
   . ../dbg/runenv.sh;
else
    echo "Can't find runenv.sh!";
    exit;
fi;
EXEC_PROG=
case $1 in
    *.scm)
	EXEC_PROG=./knox
esac

USE_LSAN_OPTIONS=${LSAN_OPTIONS:-report_objects=1,use_unaligned=1}
USE_ASAN_OPTIONS=${ASAN_OPTIONS:-malloc_context_size=20}
USE_ASAN_SYMBOLIZER_PATH=${ASAN_SYMBOLIZER_PATH:-}

MEMCHECKING=yes ASAN_SYMBOLIZER_PATH=${USE_ASAN_SYMBOLIZER_PATH} ASAN_OPTIONS=malloc_context_size=20 LSAN_OPTIONS=${USE_LSAN_OPTIONS}  ${EXEC_PROG} $* DLOAD:TRACE=yes
