.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FDCONSOLE" "1" "2016-12-11" "" ""
.
.SH "NAME"
\fBfdconsole\fR \- invoke FramerD interpeter
.
.SH "SYNOPSIS"
\fBfdconsole\fR [\fIconfig\fR|\fIfile\fR\.\.\.]
.
.SH "DESCRIPTION"
This command launches the FramerD console/terminal program, a read\-eval\-print loop which allows you to evaluate expressions and see their values\.
.
.P
The arguments to \fBfdconsole\fR are either filenames or \fIconfig\fR entries of the form \fB**setting**=*name*\fR\. The files are loaded and the config entries processed in order of appearance and config entries may specify multiple values for a setting\.
.
.P
When normally started, \fBfdconsole\fR uses the \fBeditline\fR library to provide simple command line editing and history functions\. This can be suppressed by the environment variables \fBNO_EDITLINE\fR or \fBINSIDE_EMACS\fR\.
.
.P
Some config entries may generate useful side\-effects defined by either the FramerD core or loaded modules\. Some useful built\-in config settings are:
.
.TP
\fBLOADFILE=*path*\fR
loads the file \fIpath\fR during startup\.
.
.TP
\fBMODULES=*module name*\fR
loads a FramerD module into the image and the default environment\.
.
.TP
\fBLOADPATH=*path*\fR
specifies a search path for modules, as a colon separated list of patterns where the \'%\' character is replaced by the module name\. For example \fB/opt/mods/%/module\.scm:/opt/mods/%:\fR causes the system to look for a module \fBfoo/x\fR in \fB/opt/mods/foo/x/module\.scm\fR and \fB/opt/mods/foo/x\.scm\fR\. Paths can be relative to the current directory by starting with \'\.\' and can also include ~home directory references\.
.
.TP
\fBLOGLEVEL=*level*\fR
specifies the default loglevel for notifications where level is either a positive integer or symbolic name (like \fBNOTICE\fR or \fBDEBUG\fR or \fBINFO\fR)\.
.
.SH "DIAGNOSTICS"
Returns 0 when exiting normally, 1 otherwise\. It also displays a short preamble on starting and reports its time and memory usage on exit\.
.
.SH "FILES"
On startup, \fBfdconsole\fR normally reads an \fB\.fdconfig\fR file from the user\'s home directory (if it exists)\. It can include \fBMODULES\fR or \fBLOADFILE\fR declarations\. The loading of the \fB\.fdconfig\fR file can be suppressed via the environment variable \fBFD_SKIP_DOTLOAD\fR or the config variable \fBDOTLOAD\fR\.
.
.SH "ENVIRONMENT"
As with most FramerD programs, config variables can be set through environment variables prefixed with \fBFD\fR, so \fBFD_LOGLEVEL\fR will set the default loglevel\.Ken Haase \fIkh@beingmeta\.com\fR
.
.SH "SEE ALSO"
fdexec(1), framerd_config(8)
