(in-module 'jsonout)

(define json-lisp-prefix ":")

(defambda (jsonelt value (prefix #f) (initial #f))
  (printout (unless initial ",") (if prefix prefix)
	    (if (ambiguous? value) (printout "["))
	    (do-choices (value value i)
	      (when (> i 0) (printout ","))
	      (jsonout value))
	    (if (ambiguous? value) (printout "]"))))
(define (jsonvec vector)
  (printout "[" (doseq (elt vector i)
		  (if (> i 0) (printout ", "))
		  (jsonout elt)) "]"))

(defambda (jsonfield field value (valuefn #f) (prefix #f))
  (unless (fail? value)
    (printout
      (if prefix prefix)
      (if (symbol? field)
	  (write (downcase (symbol->string field)))
	  (if (string? field) (write field)
	      (write (unparse-arg field))))
      ": "
      (if (ambiguous? value) (printout "["))
      (do-choices (value value i)
	(when (> i 0) (printout ","))
	(if valuefn
	    (jsonout (valuefn value))
	    (jsonout value)))
      (if (ambiguous? value) (printout "]")))))
(define (jsontable table (valuefn #f))
  (printout "{"
	    (let ((initial #t))
	      (do-choices (key (getkeys table) i)
		(let ((v (get table key)))
		  (when (exists? v)
		    (unless initial (printout ", "))
		    (jsonfield key v valuefn)
		    (set! initial #f)))))
	    
	    "}"))

(defambda (jsonout value)
  (cond ((ambiguous? value)
	 (printout "[" (do-choices (v value i)
			 (printout (if (> i 0) "," (jsonout v))))
		   "]"))
	((fail? value) (printout "[]"))
	((number? value) (printout value))
	((string? value) (printout (write value)))
	((vector? value) (jsonvec value))
	((eq? value #t) (printout "true"))
	((eq? value #f) (printout "false"))
	((timestamp? value) (printout (get value 'tick)))
	((oid? value)
	 (printout "\"" json-lisp-prefix (oid->string value) "\""))
	((table? value) (jsontable value))
	(else (printout "\"" json-lisp-prefix (write value) "\""))))

(module-export! '{jsonout jsonvec jsontable jsonfield jsonelt})

